### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by mikkpr** [mikkpr/cobra-caliber-2#1]
In random order:
* [x] Rewrite music system to persist through state changes
* [ ] Fine-tune current levels
* [ ] Add some kind of tutorial
* [ ] Implement visual effects (glow for neon signs and force fields etc.)
* [ ] Use and show level timers
